{-
   utoipa-axum
   Utoipa's axum bindings for seamless integration for the two

   The version of the OpenAPI document: 0.2.0
   Contact: juha7kukkonen@gmail.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Default exposing
    ( cancelJob
    , getAccount
    , getConfig
    , getJob
    , getRepoJobs
    , getRepos
    , getRev
    , handler
    , metrics
    , retryJob
    , webhook
    , webhookEndpoint
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


{-| Cancel a job

Cancels a job that is currently in progress or queued

-}
cancelJob : Uuid -> Api.Request ()
cancelJob id_path =
    Api.request
        "POST"
        "/api/v1/job/{id}/cancel"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


getAccount : Api.Request Api.Data.Account
getAccount =
    Api.request
        "GET"
        "/api/v1/account/me"
        []
        []
        []
        Nothing
        Api.Data.accountDecoder


getConfig : Api.Request Api.Data.FrontendConfig
getConfig =
    Api.request
        "GET"
        "/api/v1/config/"
        []
        []
        []
        Nothing
        Api.Data.frontendConfigDecoder


{-| Get details for a specific job

Returns job information along with GitHub data

-}
getJob : Uuid -> Api.Request Api.Data.JobResponse
getJob id_path =
    Api.request
        "GET"
        "/api/v1/job/{id}"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.jobResponseDecoder


getRepoJobs : String -> String -> Api.Request Api.Data.RepoJobs
getRepoJobs owner_path repo_path =
    Api.request
        "GET"
        "/api/v1/github/{owner}/{repo}/jobs"
        [ ( "owner", identity owner_path ), ( "repo", identity repo_path ) ]
        []
        []
        Nothing
        Api.Data.repoJobsDecoder


getRepos : Api.Request (List Api.Data.OwnerWithRepos)
getRepos =
    Api.request
        "GET"
        "/api/v1/github/repos"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.ownerWithReposDecoder)


getRev : String -> String -> String -> Api.Request Api.Data.Commit
getRev owner_path repo_path rev_path =
    Api.request
        "GET"
        "/api/v1/github/{owner}/{repo}/{rev}"
        [ ( "owner", identity owner_path ), ( "repo", identity repo_path ), ( "rev", identity rev_path ) ]
        []
        []
        Nothing
        Api.Data.commitDecoder


handler : Api.Request Api.Data.AnyType
handler =
    Api.request
        "GET"
        "/api/v1/runner/ws"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder


metrics : Api.Request String
metrics =
    Api.request
        "GET"
        "/metrics"
        []
        []
        []
        Nothing
        Json.Decode.string


{-| Retry a failed job

Creates a new job with the same configuration as the failed job

-}
retryJob : Uuid -> Api.Request Api.Data.JobResponse
retryJob id_path =
    Api.request
        "POST"
        "/api/v1/job/{id}/retry-job"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.jobResponseDecoder


webhook : Api.Request Api.Data.AnyType
webhook =
    Api.request
        "POST"
        "/api/v1/github/webhook"
        []
        []
        []
        Nothing
        Api.Data.anyTypeDecoder


webhookEndpoint : Api.Request ()
webhookEndpoint =
    Api.request
        "POST"
        "/api/v1/zitadel/actions/webhook"
        []
        []
        []
        Nothing
        (Json.Decode.succeed ())

